### ISSUE TITLE
Tree Sitter Grammar for Cedar

### ISSUE THREAD

**Issue by liamwh** [cedar-policy/highlightjs-cedar#10]
### Category

Syntax Highlighting features

### Describe the feature you'd like to request

[Tree Sitter](https://tree-sitter.github.io/tree-sitter/) Grammar for Cedar

### Describe alternatives you've considered

N/A.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by hakanson** [comment]
Is there a particular use case for Tree Sitter you are working towards, like [Zed](https://zed.dev/) support?

**Comment by liamwh** [comment]
Tree-sitter is awesome and quickly becoming the go-to way for syntax highlighting and querying the AST. Would love to see Cedar added in nvim-treesitter!

**Comment by chrnorm** [comment]
I've created an initial tree-sitter grammar for Cedar here: https://github.com/chrnorm/tree-sitter-cedar

**Comment by liamwh** [comment]
Awesome! Would you please consider opening a PR to add it to [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter)?

**Comment by john-h-kastner-aws** [comment]
Closing due the existence of https://github.com/chrnorm/tree-sitter-cedar

**Comment by liamwh** [comment]
@john-h-kastner-aws, whilst it's true that repo exists, it still isn't consumable from nvim-treesitter, please see https://github.com/chrnorm/tree-sitter-cedar/issues/1. So the problem of being able to use a treesitter parser from Neovim still exists and isn't yet solved 😬
